/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "primary-container": "#0969da",
        "secondary-fixed": "#dee3eb",
        "on-tertiary-container": "#c2ffbe",
        "error": "#ba1a1a",
        "surface-container-highest": "#dae3ee",
        "on-secondary-container": "#60656c",
        "surface-tint": "#005bc0",
        "inverse-primary": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#141c24",
        "surface-container-high": "#e0e9f4",
        "on-surface": "#141c24",
        "inverse-on-surface": "#e9f2fd",
        "surface-bright": "#f7f9ff",
        "surface-container-low": "#ecf4ff",
        "tertiary-fixed": "#a1f6a1",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#002106",
        "tertiary-fixed-dim": "#86d987",
        "on-surface-variant": "#424753",
        "on-primary-fixed": "#001a41",
        "background": "#f7f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-container": "#2a7c36",
        "tertiary": "#056220",
        "on-secondary-fixed": "#171c22",
        "surface": "#f7f9ff",
        "secondary": "#5a5f66",
        "outline": "#727785",
        "secondary-fixed-dim": "#c2c7cf",
        "on-tertiary-fixed-variant": "#005318",
        "on-primary-fixed-variant": "#004493",
        "outline-variant": "#c2c6d6",
        "surface-dim": "#d2dbe6",
        "on-primary": "#ffffff",
        "secondary-container": "#dee3eb",
        "surface-container": "#e6effa",
        "surface-variant": "#dae3ee",
        "on-primary-container": "#ecefff",
        "inverse-surface": "#29313a",
        "on-secondary-fixed-variant": "#42474e",
        "primary": "#0051ae"
      },
      fontFamily: {
        'headline': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'sans': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'space': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
